[package]
name = "backend"
version = "0.1.0"
authors = ["thebearingedge <contact@timdav.is>"]
edition = "2018"

[dependencies]
diesel = { version = "1.3.3", features = ["postgres", "uuid"] }
uuid = "0.6.5"
actix-web = "0.7.14"
dotenv = "0.13.0"
listenfd = "0.3.3"
serde = "1.0.80"
serde_json = "1.0.33"
futures = "0.1.25"
serde_derive = "1.0.80"
